### PR TITLE
Add shpec package

### PR DESCRIPTION
**Pull request by rylnd**
Pulls in a slightly modified version of shpec's own README.

### CODE REVIEW

**Comment by rylnd** [comment]
Let me know if I'm missing a step somewhere, it was a bit hard to piece together exactly what needed to be done to add a package to bpkg. So far I've simply added a package.json (https://github.com/rylnd/shpec/pull/83) and opened this PR.

**Comment by jwerle** [comment]
Looks good

**Comment by rylnd** [comment]
Related to bpkg/bpkg#44, I'm now realizing that this PR alone doesn't allow one to `bpkg install shpec`. Is there a way to get that command to work? Does it _have_ to be `bpkg install rylnd/shpec`? Was this PR totally unrelated to getting shpec listed on bpkg?

**Comment by jwerle** [comment]
Yes. All bpkg packages are namespaced by the user who owns it. If you'd like to no namespace it must be in the `bpkg` org. I can add you to the org and you can maintain a fork or transfer ownership. Let me know

**Comment by rylnd** [comment]
Ah, no, that's fine.

**Pull request merged**
