### PR TITLE
Add protobuf-parser

### PR DESCRIPTION
**Pull request by lafkpages**
A Bash library for parsing Protobuf files and `protoc` output.

Note that this is still a work-in-progress, but I thought I'd start the PR early.

Also please let me know if I did something wrong.

### CODE REVIEW

**Comment by samlikins** [comment]
Luis,

Thank you for adding your project to BPKG.  After looking at the PR, I noticed that the `title` field had a space in it. Would you please update it, replacing the space with a dash.


Thank you,

Sam

**Comment by lafkpages** [comment]
Should be fixed!

**Comment by samlikins** [comment]
Luis,

This looks like a nice addition to the repository.  If I may make a recommendation: since this is meant to be a stand alone project as well as a library, add instructions for integration within a project and/or global install.  The defined files in the `scripts` field of the project `bpkg.json` file will be added to the `deps` directory of the project requiring them, or (if globally installed) a system directory; the example provided only works if the entire repository is cloned.  It's a good idea to integrate usage into your projects README.

Also once this PR is integrated, installation instructions using BPKG would be a nice addition to your project repo.  If you have any integration questions, let us know!


Happy Coding,

Sam

**Comment by lafkpages** [comment]
> Also once this PR is integrated, installation instructions using BPKG would be a nice addition to your project repo. If you have any integration questions, let us know!

Done

**Comment by lafkpages** [comment]
Also, how would you add the package to bpkg? Would you fork my repo and have it on the bpkg org? Because that's how I understood it works by reading the code.

**Comment by samlikins** [comment]
Luis,

I appreciate the question, I think there is much room for improving the documentation for developing as well as using BPKG.  I'm attempting to enhance documents where possible. I'll make a concerted effort to add these points to the README and [website](https://bpkg.sh) soon.

If you haven't attempted running the following shell command yet, try it now.

 `bpkg install lafkpages/protobuf-parser-bash`

The project does not need to clone your project, as that would be unmanageable for all the projects already on here, as well as all the projects we hope will start integrating `bpkg.json` files.  Currently the utility will attempt to locate the specified project on GitHub, but future enhancements will integrate additional GIT sites as well as other channels.  Development of BPKG has slowed as of  recent, I've only joined within the last few months and made some needed improvements (to the utility and documentation), we're sorry for the confusion.

So you can, right now, try installing your project using BPKG.  It should perform against your repo.  Additionally, I didn't see any changes to the PR since yesterday's modification, just make sure it's pushed.  I'll attempt to keep an eye open for it, so you have time to play around with testing the installation globally and in a test project.

One last thing, as a suggestion for your project, you could condense the two files into one, which could be sourced or executed.  Take a look at the [Guidelines](https://bpkg.sh/guidelines/) document under the "Packaging best practices" section.  Placing the contents of the conversation code in one or more function(s), and the execution code in another could simplify it, then use the code I referenced above to choose what to do in the file; just a suggestion!


Happy Coding,

Sam

**Comment by lafkpages** [comment]
So if I wanna use this package in another project, in the dependencies I'd have to put "lafkpages/protobuf-parser-bash" instead of just "protobuf-parser"?

**Comment by lafkpages** [comment]
> If you would also update the `title` value in this PR, that would be appreciated also.

Done

**Comment by samlikins** [comment]
Luis,

I'm going to go ahead an merge this commit and make additional changes to it, but I strongly recommend taking time to investigate how your project is installed when running the BPKG install for your package:

`bpkg install lafkpages/protobuf-parser-bash`

The recommendation I provided you on July 9th, about integrating your three scripts into a single file, would make installing it system wide (globally) simpler and easier to subsequently use.  Additionally, if it was used within another project as a dependency, it makes it also radically simpler.  However, if you still want to maintain the separation of the `lexer` and `interpreter` into different scripts, they should be independent on both the command line and sourced into other projects; naming the scripts should make since to usage (ie: `protobuf-lexer` and `protobuf-interpreter`).

**Comment by lafkpages** [comment]
> However, if you still want to maintain the separation of the `lexer` and `interpreter` into different scripts, they should be independent on both the command line and sourced into other projects; naming the scripts should make since to usage (ie: `protobuf-lexer` and `protobuf-interpreter`).

You mean the files should each be called `protobuf-lexer` instead of just `lexer`? Or that I have to publish them as separate packages on bpkg eg. `protobuf-lexer` and `protobuf-parser`?

**Comment by lafkpages** [comment]
Ok after installing the package and looking at the `deps` directory I think I get what you're saying.

**Comment by samlikins** [comment]
Luis,

Good to hear you understand what I was saying about naming the separate files.  I would still recommend you look further into combining them into a single script for both executing (from the command line) and sourcing (from another script).

Happy Coding,

Sam

**Pull request merged**
