### PR TITLE
Add bashunit

### PR DESCRIPTION
**Pull request by Chemaclass**
## Description

I followed the instructions from https://bpkg.sh/submit/ to submit adding **[bashunit](https://github.com/Chemaclass/bashunit)** to bpkg 

Screenshot 2023-09-11 at 21 31 06

### CODE REVIEW

**Review by Tito-Kati — APPROVED** [review]

**Comment by samlikins** [comment]
@Chemaclass, that sounds like a good project to add.  I noticed that the link in the description to the project (ie: `Chemaclass/bashunit`) isn't valid and the link at the bottom of the file you're submitting doesn't have a `bpkg.json` file.  We'd love to have this project listed, but it will require this file to be in the project root for the utility to manage the project on installing systems.  Even without publishing the project on BPKG.sh, having this file allows the BPKG utility to install the project.

Once the file has been added to bashunit update us and I can make sure everything is good to merge.

On a side note, I've been using shUnit2, and have been trying to get them to accept a PR for a BPKG package file I created, and it's been months without success; so thank you for your efforts!

**Comment by Chemaclass** [comment]
Hey @samlikins, I didn't find anything related to the file `bpkg.json` in the docs. What should be the content of that file?

Regarding the the link to the project, we migrated the repo from `Chemaclass/bashunit` to `TypedDevs/bashunit` because it is not just me the person behind, but also @Tito-Kati and @khru. I updated the GitHub link in this PR changes as well.

**Comment by samlikins** [comment]
@Chemaclass, it looks good.  Let me know when you've had a chance to test it out and are ready for this addition to be merged.

**Comment by Chemaclass** [comment]
@samlikins thanks! Yes, let's merge this PR 🚀

**Review by samlikins — APPROVED** [review]

**Pull request merged**
